export class GENERAL {
  dataFillUsers(): any[] {
    return [
      {
        id: 1,
        nickname: 'glukacs0',
        password: 'PZDvbfoB',
        state: true,
      },
      {
        id: 2,
        nickname: 'mplowman1',
        password: '6Dd759',
        state: true,
      },
      {
        id: 3,
        nickname: 'alampl2',
        password: 'WcvNlAC1',
        state: false,
      },
      {
        id: 4,
        nickname: 'pcarss3',
        password: 'g6Eqhp',
        state: false,
      },
      {
        id: 5,
        nickname: 'hmerritt4',
        password: 'ig1lH9608gd',
        state: false,
      },
      {
        id: 6,
        nickname: 'lspreadbury5',
        password: 'ODmdu7A',
        state: true,
      },
      {
        id: 7,
        nickname: 'fcrane6',
        password: 'EeTm6h7BK',
        state: false,
      },
      {
        id: 8,
        nickname: 'abudden7',
        password: 'hMPGbiSU3r',
        state: true,
      },
      {
        id: 9,
        nickname: 'bsmall8',
        password: 'PO2IqyK0t',
        state: false,
      },
      {
        id: 10,
        nickname: 'gstanton9',
        password: 'DfVGxfuhq',
        state: true,
      },
      {
        id: 11,
        nickname: 'jhamleta',
        password: 'cCe5zLEKUGj1',
        state: true,
      },
      {
        id: 12,
        nickname: 'letheridgeb',
        password: 'CwfZNBDVW',
        state: false,
      },
      {
        id: 13,
        nickname: 'hhedgerc',
        password: 'AT2VpY8ARl',
        state: false,
      },
      {
        id: 14,
        nickname: 'akaresd',
        password: 'AtUCFSWYtq',
        state: true,
      },
      {
        id: 15,
        nickname: 'kmcwhine',
        password: 'iQWaXWcmRIi',
        state: false,
      },
      {
        id: 16,
        nickname: 'cconveryf',
        password: 'CtbVUZ7nHRy',
        state: true,
      },
      {
        id: 17,
        nickname: 'whuxstepg',
        password: 'NjsQRGov2T',
        state: false,
      },
      {
        id: 18,
        nickname: 'fdowh',
        password: 'X1LgOaF9A3',
        state: false,
      },
      {
        id: 19,
        nickname: 'lbethunei',
        password: 'R3m1W8X4',
        state: true,
      },
      {
        id: 20,
        nickname: 'djiraj',
        password: 'czD8PctTf',
        state: false,
      },
      {
        id: 21,
        nickname: 'ndictyk',
        password: 'CLAAq4',
        state: false,
      },
      {
        id: 22,
        nickname: 'lcarassl',
        password: 's6SNWQ',
        state: true,
      },
      {
        id: 23,
        nickname: 'lquirkem',
        password: 'cEKOivfFT',
        state: false,
      },
      {
        id: 24,
        nickname: 'iponnsettn',
        password: 'S2BHyNcMEL',
        state: true,
      },
      {
        id: 25,
        nickname: 'ngiabuccio',
        password: '3KaZgGBF7',
        state: true,
      },
      {
        id: 26,
        nickname: 'jhunnywellp',
        password: 'Bwd4ewg0gZKI',
        state: true,
      },
      {
        id: 27,
        nickname: 'ddruceq',
        password: '1dUv0dHr',
        state: true,
      },
      {
        id: 28,
        nickname: 'gkuhnhardtr',
        password: 'qNOKl0',
        state: true,
      },
      {
        id: 29,
        nickname: 'edodss',
        password: 'VTXHyn3',
        state: true,
      },
      {
        id: 30,
        nickname: 'bfrantzt',
        password: 'GoCIXx9h0Mw',
        state: false,
      },
      {
        id: 31,
        nickname: 'hpartonu',
        password: 'LorHeiKSw',
        state: false,
      },
      {
        id: 32,
        nickname: 'droddv',
        password: 'ZnACs9J7Osrs',
        state: false,
      },
      {
        id: 33,
        nickname: 'fsaltmarshw',
        password: 'WNSCt0W9mD1',
        state: false,
      },
      {
        id: 34,
        nickname: 'mduerdenx',
        password: 'kRbtODl',
        state: false,
      },
      {
        id: 35,
        nickname: 'jwastally',
        password: 'Pc95EtW',
        state: false,
      },
      {
        id: 36,
        nickname: 'wruprechtz',
        password: 'Lj433k',
        state: true,
      },
      {
        id: 37,
        nickname: 'tpedrocchi10',
        password: '9N8byeb',
        state: true,
      },
      {
        id: 38,
        nickname: 'phugle11',
        password: 'o80KW8ujVY',
        state: false,
      },
      {
        id: 39,
        nickname: 'dgershom12',
        password: 'bVjMoMd6I',
        state: true,
      },
      {
        id: 40,
        nickname: 'alambert13',
        password: 'L2eIzLX2',
        state: true,
      },
      {
        id: 41,
        nickname: 'mgwinnett14',
        password: '8nfNzZ',
        state: true,
      },
      {
        id: 42,
        nickname: 'elorriman15',
        password: 'FzixVGqu',
        state: false,
      },
      {
        id: 43,
        nickname: 'jhannant16',
        password: 'J948tRu',
        state: false,
      },
      {
        id: 44,
        nickname: 'cewin17',
        password: 'ccM3KAEt',
        state: false,
      },
      {
        id: 45,
        nickname: 'gcuddon18',
        password: 'wqzBIAPcpFs',
        state: false,
      },
      {
        id: 46,
        nickname: 'tord19',
        password: 'TSIwSi',
        state: false,
      },
      {
        id: 47,
        nickname: 'bprobet1a',
        password: 'ty3xKpd',
        state: false,
      },
      {
        id: 48,
        nickname: 'lmacdirmid1b',
        password: 'Ly70coFeA',
        state: false,
      },
      {
        id: 49,
        nickname: 'hspensley1c',
        password: 'oHbRDek4',
        state: true,
      },
      {
        id: 50,
        nickname: 'jdowdall1d',
        password: 'jAubyzgs5EH',
        state: true,
      },
      {
        id: 51,
        nickname: 'spavelin1e',
        password: 'U8pXGVdN8O',
        state: true,
      },
      {
        id: 52,
        nickname: 'gwahncke1f',
        password: '1z8IAS2',
        state: true,
      },
      {
        id: 53,
        nickname: 'nhelm1g',
        password: 'Ga661wxP8',
        state: false,
      },
      {
        id: 54,
        nickname: 'lcarruth1h',
        password: 'pxjJCkmFGHNx',
        state: false,
      },
      {
        id: 55,
        nickname: 'bhaestier1i',
        password: 'V9ABC6K',
        state: true,
      },
      {
        id: 56,
        nickname: 'mblastock1j',
        password: 'y1UTQjqNMSQ',
        state: false,
      },
      {
        id: 57,
        nickname: 'gdonwell1k',
        password: 'oiyM8M',
        state: true,
      },
      {
        id: 58,
        nickname: 'dmackison1l',
        password: '0QSUOhwS6',
        state: true,
      },
      {
        id: 59,
        nickname: 'meake1m',
        password: 'E28FUoT',
        state: false,
      },
      {
        id: 60,
        nickname: 'dliepins1n',
        password: 'kJj20N',
        state: true,
      },
      {
        id: 61,
        nickname: 'rrizzotto1o',
        password: 'LDxuWhO7p',
        state: true,
      },
      {
        id: 62,
        nickname: 'ebitcheno1p',
        password: '4UAAnrLY',
        state: false,
      },
      {
        id: 63,
        nickname: 'grickell1q',
        password: 'm3pIYKg7mr3',
        state: true,
      },
      {
        id: 64,
        nickname: 'lfolkerd1r',
        password: 'HJ5RhDX',
        state: true,
      },
      {
        id: 65,
        nickname: 'asebborn1s',
        password: 'NHFA4s3b01TD',
        state: false,
      },
      {
        id: 66,
        nickname: 'carmin1t',
        password: 'aunhH4TKV1',
        state: true,
      },
      {
        id: 67,
        nickname: 'dhaggith1u',
        password: 'b5XSL1',
        state: false,
      },
      {
        id: 68,
        nickname: 'xmissington1v',
        password: 'e8SZwD6oQ',
        state: true,
      },
      {
        id: 69,
        nickname: 'rcarleman1w',
        password: 'B4i9Ia2Zq',
        state: false,
      },
      {
        id: 70,
        nickname: 'bkaygill1x',
        password: 'EDVDnKD5k',
        state: true,
      },
      {
        id: 71,
        nickname: 'nbrettle1y',
        password: 'CCeHVn',
        state: true,
      },
      {
        id: 72,
        nickname: 'rmoules1z',
        password: 'uzQ0S1IB3',
        state: true,
      },
      {
        id: 73,
        nickname: 'aamis20',
        password: 'XFTiRsNwlVXy',
        state: false,
      },
      {
        id: 74,
        nickname: 'dpailin21',
        password: 'VsftjtUtloA2',
        state: true,
      },
      {
        id: 75,
        nickname: 'otremberth22',
        password: 'BLjFRs6il',
        state: true,
      },
      {
        id: 76,
        nickname: 'chearns23',
        password: 'ZeczyDHGnBU4',
        state: true,
      },
      {
        id: 77,
        nickname: 'hfraczak24',
        password: 'eclVCp',
        state: true,
      },
      {
        id: 78,
        nickname: 'gbruton25',
        password: 'rSMjb07XfweF',
        state: true,
      },
      {
        id: 79,
        nickname: 'brosenfield26',
        password: 'tFSQctQdepF',
        state: false,
      },
      {
        id: 80,
        nickname: 'aallanby27',
        password: 'Ps9Dfw0GA',
        state: false,
      },
      {
        id: 81,
        nickname: 'mgeratasch28',
        password: 'B86H8Im8IU',
        state: false,
      },
      {
        id: 82,
        nickname: 'dantognoni29',
        password: 'Gv6u4yQ1Bd',
        state: true,
      },
      {
        id: 83,
        nickname: 'blelievre2a',
        password: 'wDiAbMfzc',
        state: false,
      },
      {
        id: 84,
        nickname: 'nclendinning2b',
        password: 'NeBUY3',
        state: true,
      },
      {
        id: 85,
        nickname: 'dgething2c',
        password: 'o3Mmtcac11O9',
        state: true,
      },
      {
        id: 86,
        nickname: 'epenning2d',
        password: 'LwJHFSvGy45F',
        state: false,
      },
      {
        id: 87,
        nickname: 'kkiely2e',
        password: '2FBDX7OKDd',
        state: true,
      },
      {
        id: 88,
        nickname: 'vfacey2f',
        password: 'WVCwLybE',
        state: false,
      },
      {
        id: 89,
        nickname: 'pbilsborrow2g',
        password: 'rITsXKQa',
        state: true,
      },
      {
        id: 90,
        nickname: 'soliphand2h',
        password: 'qssL6XqNgY',
        state: true,
      },
      {
        id: 91,
        nickname: 'mbamlett2i',
        password: 'bkkHH9qs',
        state: true,
      },
      {
        id: 92,
        nickname: 'kahern2j',
        password: 'mBbjn7jz',
        state: false,
      },
      {
        id: 93,
        nickname: 'gmcparland2k',
        password: 'tnf9tbAaM5',
        state: false,
      },
      {
        id: 94,
        nickname: 'rgarbett2l',
        password: 'ZRdZjwAgez',
        state: false,
      },
      {
        id: 95,
        nickname: 'amaciver2m',
        password: 'sDrGq6Nh',
        state: false,
      },
      {
        id: 96,
        nickname: 'fstaniforth2n',
        password: 'oZcDbaalnZ',
        state: false,
      },
      {
        id: 97,
        nickname: 'jmcnysche2o',
        password: '5ItFuaT2',
        state: true,
      },
      {
        id: 98,
        nickname: 'mfrancis2p',
        password: 'oPSZXj6',
        state: false,
      },
      {
        id: 99,
        nickname: 'imunt2q',
        password: 'Twgf8F783cS',
        state: true,
      },
      {
        id: 100,
        nickname: 'hcossum2r',
        password: 'hAehYxlnUVU',
        state: true,
      },
    ];
  }
}
