export class GENERAL {
  dataFillUsers(): any[] {
    return [
      {
        id: 1,
        nickname: 'glukacs0',
        password: 'PZDvbfoB',
        state: true,
      },
      {
        id: 2,
        nickname: 'mplowman1',
        password: '6Dd759',
        state: true,
      },
      {
        id: 3,
        nickname: 'alampl2',
        password: 'WcvNlAC1',
        state: false,
      },
      {
        id: 4,
        nickname: 'pcarss3',
        password: 'g6Eqhp',
        state: false,
      },
      {
        id: 5,
        nickname: 'hmerritt4',
        password: 'ig1lH9608gd',
        state: false,
      },
      {
        id: 6,
        nickname: 'lspreadbury5',
        password: 'ODmdu7A',
        state: true,
      },
      {
        id: 7,
        nickname: 'fcrane6',
        password: 'EeTm6h7BK',
        state: false,
      },
      {
        id: 8,
        nickname: 'abudden7',
        password: 'hMPGbiSU3r',
        state: true,
      },
      {
        id: 9,
        nickname: 'bsmall8',
        password: 'PO2IqyK0t',
        state: false,
      },
      {
        id: 10,
        nickname: 'gstanton9',
        password: 'DfVGxfuhq',
        state: true,
      },
      {
        id: 11,
        nickname: 'jhamleta',
        password: 'cCe5zLEKUGj1',
        state: true,
      },
      {
        id: 12,
        nickname: 'letheridgeb',
        password: 'CwfZNBDVW',
        state: false,
      },
      {
        id: 13,
        nickname: 'hhedgerc',
        password: 'AT2VpY8ARl',
        state: false,
      },
      {
        id: 14,
        nickname: 'akaresd',
        password: 'AtUCFSWYtq',
        state: true,
      },
      {
        id: 15,
        nickname: 'kmcwhine',
        password: 'iQWaXWcmRIi',
        state: false,
      },
      {
        id: 16,
        nickname: 'cconveryf',
        password: 'CtbVUZ7nHRy',
        state: true,
      },
      {
        id: 17,
        nickname: 'whuxstepg',
        password: 'NjsQRGov2T',
        state: false,
      },
      {
        id: 18,
        nickname: 'fdowh',
        password: 'X1LgOaF9A3',
        state: false,
      },
      {
        id: 19,
        nickname: 'lbethunei',
        password: 'R3m1W8X4',
        state: true,
      },
      {
        id: 20,
        nickname: 'djiraj',
        password: 'czD8PctTf',
        state: false,
      },
      {
        id: 21,
        nickname: 'ndictyk',
        password: 'CLAAq4',
        state: false,
      },
      {
        id: 22,
        nickname: 'lcarassl',
        password: 's6SNWQ',
        state: true,
      },
      {
        id: 23,
        nickname: 'lquirkem',
        password: 'cEKOivfFT',
        state: false,
      },
      {
        id: 24,
        nickname: 'iponnsettn',
        password: 'S2BHyNcMEL',
        state: true,
      },
      {
        id: 25,
        nickname: 'ngiabuccio',
        password: '3KaZgGBF7',
        state: true,
      },
      {
        id: 26,
        nickname: 'jhunnywellp',
        password: 'Bwd4ewg0gZKI',
        state: true,
      },
      {
        id: 27,
        nickname: 'ddruceq',
        password: '1dUv0dHr',
        state: true,
      },
      {
        id: 28,
        nickname: 'gkuhnhardtr',
        password: 'qNOKl0',
        state: true,
      },
      {
        id: 29,
        nickname: 'edodss',
        password: 'VTXHyn3',
        state: true,
      },
      {
        id: 30,
        nickname: 'bfrantzt',
        password: 'GoCIXx9h0Mw',
        state: false,
      },
      {
        id: 31,
        nickname: 'hpartonu',
        password: 'LorHeiKSw',
        state: false,
      },
      {
        id: 32,
        nickname: 'droddv',
        password: 'ZnACs9J7Osrs',
        state: false,
      },
      {
        id: 33,
        nickname: 'fsaltmarshw',
        password: 'WNSCt0W9mD1',
        state: false,
      },
      {
        id: 34,
        nickname: 'mduerdenx',
        password: 'kRbtODl',
        state: false,
      },
      {
        id: 35,
        nickname: 'jwastally',
        password: 'Pc95EtW',
        state: false,
      },
      {
        id: 36,
        nickname: 'wruprechtz',
        password: 'Lj433k',
        state: true,
      },
      {
        id: 37,
        nickname: 'tpedrocchi10',
        password: '9N8byeb',
        state: true,
      },
      {
        id: 38,
        nickname: 'phugle11',
        password: 'o80KW8ujVY',
        state: false,
      },
      {
        id: 39,
        nickname: 'dgershom12',
        password: 'bVjMoMd6I',
        state: true,
      },
      {
        id: 40,
        nickname: 'alambert13',
        password: 'L2eIzLX2',
        state: true,
      },
      {
        id: 41,
        nickname: 'mgwinnett14',
        password: '8nfNzZ',
        state: true,
      },
      {
        id: 42,
        nickname: 'elorriman15',
        password: 'FzixVGqu',
        state: false,
      },
      {
        id: 43,
        nickname: 'jhannant16',
        password: 'J948tRu',
        state: false,
      },
      {
        id: 44,
        nickname: 'cewin17',
        password: 'ccM3KAEt',
        state: false,
      },
      {
        id: 45,
        nickname: 'gcuddon18',
        password: 'wqzBIAPcpFs',
        state: false,
      },
      {
        id: 46,
        nickname: 'tord19',
        password: 'TSIwSi',
        state: false,
      },
      {
        id: 47,
        nickname: 'bprobet1a',
        password: 'ty3xKpd',
        state: false,
      },
      {
        id: 48,
        nickname: 'lmacdirmid1b',
        password: 'Ly70coFeA',
        state: false,
      },
      {
        id: 49,
        nickname: 'hspensley1c',
        password: 'oHbRDek4',
        state: true,
      },
      {
        id: 50,
        nickname: 'jdowdall1d',
        password: 'jAubyzgs5EH',
        state: true,
      },
      {
        id: 51,
        nickname: 'spavelin1e',
        password: 'U8pXGVdN8O',
        state: true,
      },
      {
        id: 52,
        nickname: 'gwahncke1f',
        password: '1z8IAS2',
        state: true,
      },
      {
        id: 53,
        nickname: 'nhelm1g',
        password: 'Ga661wxP8',
        state: false,
      },
      {
        id: 54,
        nickname: 'lcarruth1h',
        password: 'pxjJCkmFGHNx',
        state: false,
      },
      {
        id: 55,
        nickname: 'bhaestier1i',
        password: 'V9ABC6K',
        state: true,
      },
      {
        id: 56,
        nickname: 'mblastock1j',
        password: 'y1UTQjqNMSQ',
        state: false,
      },
      {
        id: 57,
        nickname: 'gdonwell1k',
        password: 'oiyM8M',
        state: true,
      },
      {
        id: 58,
        nickname: 'dmackison1l',
        password: '0QSUOhwS6',
        state: true,
      },
      {
        id: 59,
        nickname: 'meake1m',
        password: 'E28FUoT',
        state: false,
      },
      {
        id: 60,
        nickname: 'dliepins1n',
        password: 'kJj20N',
        state: true,
      },
      {
        id: 61,
        nickname: 'rrizzotto1o',
        password: 'LDxuWhO7p',
        state: true,
      },
      {
        id: 62,
        nickname: 'ebitcheno1p',
        password: '4UAAnrLY',
        state: false,
      },
      {
        id: 63,
        nickname: 'grickell1q',
        password: 'm3pIYKg7mr3',
        state: true,
      },
      {
        id: 64,
        nickname: 'lfolkerd1r',
        password: 'HJ5RhDX',
        state: true,
      },
      {
        id: 65,
        nickname: 'asebborn1s',
        password: 'NHFA4s3b01TD',
        state: false,
      },
      {
        id: 66,
        nickname: 'carmin1t',
        password: 'aunhH4TKV1',
        state: true,
      },
      {
        id: 67,
        nickname: 'dhaggith1u',
        password: 'b5XSL1',
        state: false,
      },
      {
        id: 68,
        nickname: 'xmissington1v',
        password: 'e8SZwD6oQ',
        state: true,
      },
      {
        id: 69,
        nickname: 'rcarleman1w',
        password: 'B4i9Ia2Zq',
        state: false,
      },
      {
        id: 70,
        nickname: 'bkaygill1x',
        password: 'EDVDnKD5k',
        state: true,
      },
      {
        id: 71,
        nickname: 'nbrettle1y',
        password: 'CCeHVn',
        state: true,
      },
      {
        id: 72,
        nickname: 'rmoules1z',
        password: 'uzQ0S1IB3',
        state: true,
      },
      {
        id: 73,
        nickname: 'aamis20',
        password: 'XFTiRsNwlVXy',
        state: false,
      },
      {
        id: 74,
        nickname: 'dpailin21',
        password: 'VsftjtUtloA2',
        state: true,
      },
      {
        id: 75,
        nickname: 'otremberth22',
        password: 'BLjFRs6il',
        state: true,
      },
      {
        id: 76,
        nickname: 'chearns23',
        password: 'ZeczyDHGnBU4',
        state: true,
      },
      {
        id: 77,
        nickname: 'hfraczak24',
        password: 'eclVCp',
        state: true,
      },
      {
        id: 78,
        nickname: 'gbruton25',
        password: 'rSMjb07XfweF',
        state: true,
      },
      {
        id: 79,
        nickname: 'brosenfield26',
        password: 'tFSQctQdepF',
        state: false,
      },
      {
        id: 80,
        nickname: 'aallanby27',
        password: 'Ps9Dfw0GA',
        state: false,
      },
      {
        id: 81,
        nickname: 'mgeratasch28',
        password: 'B86H8Im8IU',
        state: false,
      },
      {
        id: 82,
        nickname: 'dantognoni29',
        password: 'Gv6u4yQ1Bd',
        state: true,
      },
      {
        id: 83,
        nickname: 'blelievre2a',
        password: 'wDiAbMfzc',
        state: false,
      },
      {
        id: 84,
        nickname: 'nclendinning2b',
        password: 'NeBUY3',
        state: true,
      },
      {
        id: 85,
        nickname: 'dgething2c',
        password: 'o3Mmtcac11O9',
        state: true,
      },
      {
        id: 86,
        nickname: 'epenning2d',
        password: 'LwJHFSvGy45F',
        state: false,
      },
      {
        id: 87,
        nickname: 'kkiely2e',
        password: '2FBDX7OKDd',
        state: true,
      },
      {
        id: 88,
        nickname: 'vfacey2f',
        password: 'WVCwLybE',
        state: false,
      },
      {
        id: 89,
        nickname: 'pbilsborrow2g',
        password: 'rITsXKQa',
        state: true,
      },
      {
        id: 90,
        nickname: 'soliphand2h',
        password: 'qssL6XqNgY',
        state: true,
      },
      {
        id: 91,
        nickname: 'mbamlett2i',
        password: 'bkkHH9qs',
        state: true,
      },
      {
        id: 92,
        nickname: 'kahern2j',
        password: 'mBbjn7jz',
        state: false,
      },
      {
        id: 93,
        nickname: 'gmcparland2k',
        password: 'tnf9tbAaM5',
        state: false,
      },
      {
        id: 94,
        nickname: 'rgarbett2l',
        password: 'ZRdZjwAgez',
        state: false,
      },
      {
        id: 95,
        nickname: 'amaciver2m',
        password: 'sDrGq6Nh',
        state: false,
      },
      {
        id: 96,
        nickname: 'fstaniforth2n',
        password: 'oZcDbaalnZ',
        state: false,
      },
      {
        id: 97,
        nickname: 'jmcnysche2o',
        password: '5ItFuaT2',
        state: true,
      },
      {
        id: 98,
        nickname: 'mfrancis2p',
        password: 'oPSZXj6',
        state: false,
      },
      {
        id: 99,
        nickname: 'imunt2q',
        password: 'Twgf8F783cS',
        state: true,
      },
      {
        id: 100,
        nickname: 'hcossum2r',
        password: 'hAehYxlnUVU',
        state: true,
      },
    ];
  }

  dataFillBuys(): any[] {
    return [
      {
        id: 1,
        proveedor: 'Vinder',
        fecha_emision: '2/24/2020',
        fecha_cancelacion: null,
        empleado: 'Bonnee Manuelli',
        total: 187371.81,
      },
      {
        id: 2,
        proveedor: 'Trilith',
        fecha_emision: '9/28/2020',
        fecha_cancelacion: null,
        empleado: 'Yorgos Koschek',
        total: 743961.32,
      },
      {
        id: 3,
        proveedor: 'Flashpoint',
        fecha_emision: '7/11/2020',
        fecha_cancelacion: null,
        empleado: 'Elaina Sowray',
        total: 185053.3,
      },
      {
        id: 4,
        proveedor: 'Oyondu',
        fecha_emision: '9/20/2020',
        fecha_cancelacion: null,
        empleado: 'Patric Habershaw',
        total: 611679.17,
      },
      {
        id: 5,
        proveedor: 'Bubbletube',
        fecha_emision: '6/18/2020',
        fecha_cancelacion: null,
        empleado: 'Anastasie Tuxell',
        total: 828798.0,
      },
      {
        id: 6,
        proveedor: 'Gigabox',
        fecha_emision: '6/2/2020',
        fecha_cancelacion: null,
        empleado: 'Maribelle Clipston',
        total: 149986.46,
      },
      {
        id: 7,
        proveedor: 'Meemm',
        fecha_emision: '11/7/2020',
        fecha_cancelacion: null,
        empleado: 'Thorpe Martyn',
        total: 621068.45,
      },
      {
        id: 8,
        proveedor: 'Viva',
        fecha_emision: '7/6/2020',
        fecha_cancelacion: null,
        empleado: 'Felice Langlois',
        total: 876399.34,
      },
      {
        id: 9,
        proveedor: 'Demivee',
        fecha_emision: '6/15/2020',
        fecha_cancelacion: null,
        empleado: 'Pavia Alster',
        total: 834672.7,
      },
      {
        id: 10,
        proveedor: 'Jabbersphere',
        fecha_emision: '6/13/2020',
        fecha_cancelacion: null,
        empleado: 'Mike Velareal',
        total: 543642.12,
      },
      {
        id: 11,
        proveedor: 'Thoughtblab',
        fecha_emision: '3/5/2020',
        fecha_cancelacion: null,
        empleado: 'Fleur Cail',
        total: 467503.91,
      },
      {
        id: 12,
        proveedor: 'Kazu',
        fecha_emision: '11/5/2020',
        fecha_cancelacion: null,
        empleado: 'Vonnie Tomlinson',
        total: 107494.46,
      },
      {
        id: 13,
        proveedor: 'Feedfire',
        fecha_emision: '5/14/2020',
        fecha_cancelacion: null,
        empleado: 'Boycey Bayston',
        total: 200957.39,
      },
      {
        id: 14,
        proveedor: 'Digitube',
        fecha_emision: '1/28/2020',
        fecha_cancelacion: null,
        empleado: 'Myrvyn Artus',
        total: 970534.14,
      },
      {
        id: 15,
        proveedor: 'Roombo',
        fecha_emision: '8/23/2020',
        fecha_cancelacion: null,
        empleado: 'Esta Beane',
        total: 718052.23,
      },
      {
        id: 16,
        proveedor: 'Quimm',
        fecha_emision: '3/20/2020',
        fecha_cancelacion: null,
        empleado: 'Elisa Dalton',
        total: 906820.93,
      },
      {
        id: 17,
        proveedor: 'Quamba',
        fecha_emision: '6/16/2020',
        fecha_cancelacion: null,
        empleado: 'Bryna Swyn',
        total: 337057.43,
      },
      {
        id: 18,
        proveedor: 'Wikibox',
        fecha_emision: '10/10/2020',
        fecha_cancelacion: null,
        empleado: 'Dougy Episcopio',
        total: 960175.17,
      },
      {
        id: 19,
        proveedor: 'Zoovu',
        fecha_emision: '3/18/2020',
        fecha_cancelacion: null,
        empleado: 'Mead Duddin',
        total: 170842.03,
      },
      {
        id: 20,
        proveedor: 'Cogibox',
        fecha_emision: '4/13/2020',
        fecha_cancelacion: null,
        empleado: 'Mort Devon',
        total: 279048.27,
      },
      {
        id: 21,
        proveedor: 'Livefish',
        fecha_emision: '12/31/2019',
        fecha_cancelacion: null,
        empleado: 'Lexie Gimbrett',
        total: 370513.7,
      },
      {
        id: 22,
        proveedor: 'Blognation',
        fecha_emision: '7/25/2020',
        fecha_cancelacion: null,
        empleado: 'Torrence Simak',
        total: 136238.63,
      },
      {
        id: 23,
        proveedor: 'Edgetag',
        fecha_emision: '11/27/2019',
        fecha_cancelacion: null,
        empleado: 'Ferrell Church',
        total: 646153.9,
      },
      {
        id: 24,
        proveedor: 'Gigashots',
        fecha_emision: '11/26/2019',
        fecha_cancelacion: null,
        empleado: 'Mitchell Camerana',
        total: 962740.76,
      },
      {
        id: 25,
        proveedor: 'Babblestorm',
        fecha_emision: '11/23/2019',
        fecha_cancelacion: null,
        empleado: 'Robb Biggins',
        total: 231258.97,
      },
      {
        id: 26,
        proveedor: 'Linklinks',
        fecha_emision: '7/16/2020',
        fecha_cancelacion: null,
        empleado: 'Thaxter Gaine',
        total: 402615.27,
      },
      {
        id: 27,
        proveedor: 'Dabvine',
        fecha_emision: '1/10/2020',
        fecha_cancelacion: null,
        empleado: 'Ulises Probin',
        total: 695598.3,
      },
      {
        id: 28,
        proveedor: 'Gigashots',
        fecha_emision: '6/16/2020',
        fecha_cancelacion: null,
        empleado: 'Helenelizabeth Comins',
        total: 475742.49,
      },
      {
        id: 29,
        proveedor: 'Tazz',
        fecha_emision: '2/2/2020',
        fecha_cancelacion: null,
        empleado: 'Gabi Twinbrow',
        total: 901269.32,
      },
      {
        id: 30,
        proveedor: 'Devify',
        fecha_emision: '2/21/2020',
        fecha_cancelacion: null,
        empleado: 'April Rumens',
        total: 428803.0,
      },
      {
        id: 31,
        proveedor: 'Bluezoom',
        fecha_emision: '8/13/2020',
        fecha_cancelacion: '2/6/2020',
        empleado: 'Alyse Bolderson',
        total: 164282.4,
      },
      {
        id: 32,
        proveedor: 'Shufflester',
        fecha_emision: '2/18/2020',
        fecha_cancelacion: null,
        empleado: 'Gavin Ensten',
        total: 140586.6,
      },
      {
        id: 33,
        proveedor: 'Vinder',
        fecha_emision: '2/15/2020',
        fecha_cancelacion: null,
        empleado: 'Evelina Daen',
        total: 635953.0,
      },
      {
        id: 34,
        proveedor: 'Lazz',
        fecha_emision: '7/10/2020',
        fecha_cancelacion: '5/30/2020',
        empleado: 'Sheilah Grewe',
        total: 55172.46,
      },
      {
        id: 35,
        proveedor: 'Browsebug',
        fecha_emision: '8/2/2020',
        fecha_cancelacion: null,
        empleado: 'Leland Paskin',
        total: 729699.59,
      },
      {
        id: 36,
        proveedor: 'Livefish',
        fecha_emision: '9/9/2020',
        fecha_cancelacion: null,
        empleado: 'Ciel Rylands',
        total: 762999.67,
      },
      {
        id: 37,
        proveedor: 'Ainyx',
        fecha_emision: '1/12/2020',
        fecha_cancelacion: '6/9/2020',
        empleado: 'Marv Lambal',
        total: 213559.5,
      },
      {
        id: 38,
        proveedor: 'Voolia',
        fecha_emision: '3/5/2020',
        fecha_cancelacion: null,
        empleado: 'Justus Hazeup',
        total: 773679.0,
      },
      {
        id: 39,
        proveedor: 'Pixoboo',
        fecha_emision: '7/17/2020',
        fecha_cancelacion: '4/26/2020',
        empleado: 'Lucille Drust',
        total: 405214.62,
      },
      {
        id: 40,
        proveedor: 'Devshare',
        fecha_emision: '5/11/2020',
        fecha_cancelacion: null,
        empleado: 'Mignonne OShevlan',
        total: 995032.09,
      },
      {
        id: 41,
        proveedor: 'Flipopia',
        fecha_emision: '10/30/2020',
        fecha_cancelacion: null,
        empleado: 'Josias Jauncey',
        total: 303277.0,
      },
      {
        id: 42,
        proveedor: 'Realbuzz',
        fecha_emision: '11/4/2020',
        fecha_cancelacion: null,
        empleado: 'Raymund Lummasana',
        total: 844477.45,
      },
      {
        id: 43,
        proveedor: 'Nlounge',
        fecha_emision: '12/25/2019',
        fecha_cancelacion: null,
        empleado: 'Adella Geoghegan',
        total: 974077.23,
      },
      {
        id: 44,
        proveedor: 'Gabvine',
        fecha_emision: '9/14/2020',
        fecha_cancelacion: null,
        empleado: 'Mic Soame',
        total: 614967.82,
      },
      {
        id: 45,
        proveedor: 'Yamia',
        fecha_emision: '12/9/2019',
        fecha_cancelacion: null,
        empleado: 'Tera Kliment',
        total: 154957.68,
      },
      {
        id: 46,
        proveedor: 'Devcast',
        fecha_emision: '8/1/2020',
        fecha_cancelacion: null,
        empleado: 'Elden Swetmore',
        total: 381735.46,
      },
      {
        id: 47,
        proveedor: 'Thoughtstorm',
        fecha_emision: '2/6/2020',
        fecha_cancelacion: null,
        empleado: 'Camila Fritz',
        total: 339719.38,
      },
      {
        id: 48,
        proveedor: 'Rhyzio',
        fecha_emision: '6/10/2020',
        fecha_cancelacion: null,
        empleado: 'Jory Zollner',
        total: 877708.06,
      },
      {
        id: 49,
        proveedor: 'Buzzdog',
        fecha_emision: '4/10/2020',
        fecha_cancelacion: null,
        empleado: 'Art Hiley',
        total: 783214.83,
      },
      {
        id: 50,
        proveedor: 'Lazzy',
        fecha_emision: '2/13/2020',
        fecha_cancelacion: null,
        empleado: 'Leoline Attenborrow',
        total: 974073.42,
      },
      {
        id: 51,
        proveedor: 'Leexo',
        fecha_emision: '2/29/2020',
        fecha_cancelacion: null,
        empleado: 'Althea Mournian',
        total: 578433.88,
      },
      {
        id: 52,
        proveedor: 'Edgeblab',
        fecha_emision: '9/8/2020',
        fecha_cancelacion: null,
        empleado: 'Kylie Dickens',
        total: 510870.0,
      },
      {
        id: 53,
        proveedor: 'Mudo',
        fecha_emision: '6/24/2020',
        fecha_cancelacion: null,
        empleado: 'Ardyth St. Leger',
        total: 809065.73,
      },
      {
        id: 54,
        proveedor: 'Centimia',
        fecha_emision: '6/28/2020',
        fecha_cancelacion: null,
        empleado: 'Fionnula Nance',
        total: 921808.12,
      },
      {
        id: 55,
        proveedor: 'Rhynoodle',
        fecha_emision: '6/8/2020',
        fecha_cancelacion: null,
        empleado: 'Brooks Titterington',
        total: 670394.04,
      },
      {
        id: 56,
        proveedor: 'Yotz',
        fecha_emision: '3/2/2020',
        fecha_cancelacion: null,
        empleado: 'Maximilian Gewer',
        total: 681149.73,
      },
      {
        id: 57,
        proveedor: 'Eazzy',
        fecha_emision: '1/7/2020',
        fecha_cancelacion: '7/1/2020',
        empleado: 'Fanni Betonia',
        total: 884253.36,
      },
      {
        id: 58,
        proveedor: 'Vipe',
        fecha_emision: '10/20/2020',
        fecha_cancelacion: null,
        empleado: 'Arlee McKeurton',
        total: 978604.64,
      },
      {
        id: 59,
        proveedor: 'InnoZ',
        fecha_emision: '6/13/2020',
        fecha_cancelacion: null,
        empleado: 'Raleigh Gobert',
        total: 251071.35,
      },
      {
        id: 60,
        proveedor: 'Meedoo',
        fecha_emision: '4/24/2020',
        fecha_cancelacion: null,
        empleado: 'Winifred Willcott',
        total: 789708.75,
      },
      {
        id: 61,
        proveedor: 'Zoomcast',
        fecha_emision: '6/29/2020',
        fecha_cancelacion: null,
        empleado: 'Christiano Crannage',
        total: 386569.01,
      },
      {
        id: 62,
        proveedor: 'Jetwire',
        fecha_emision: '2/9/2020',
        fecha_cancelacion: null,
        empleado: 'Jim Sones',
        total: 491159.68,
      },
      {
        id: 63,
        proveedor: 'Janyx',
        fecha_emision: '6/24/2020',
        fecha_cancelacion: null,
        empleado: 'Lauri Ennew',
        total: 684230.11,
      },
      {
        id: 64,
        proveedor: 'Thoughtbeat',
        fecha_emision: '11/14/2020',
        fecha_cancelacion: null,
        empleado: 'Gradeigh Atwell',
        total: 850346.68,
      },
      {
        id: 65,
        proveedor: 'Skalith',
        fecha_emision: '5/7/2020',
        fecha_cancelacion: null,
        empleado: 'Laetitia Coal',
        total: 89800.99,
      },
      {
        id: 66,
        proveedor: 'Topiczoom',
        fecha_emision: '2/14/2020',
        fecha_cancelacion: null,
        empleado: 'Wilmar Puttrell',
        total: 856341.68,
      },
      {
        id: 67,
        proveedor: 'Skyble',
        fecha_emision: '3/1/2020',
        fecha_cancelacion: null,
        empleado: 'Rowena Gras',
        total: 184257.13,
      },
      {
        id: 68,
        proveedor: 'Podcat',
        fecha_emision: '1/1/2020',
        fecha_cancelacion: null,
        empleado: 'Herculie Lytle',
        total: 966306.02,
      },
      {
        id: 69,
        proveedor: 'Jabbercube',
        fecha_emision: '6/30/2020',
        fecha_cancelacion: null,
        empleado: 'Porty Thomton',
        total: 200274.62,
      },
      {
        id: 70,
        proveedor: 'Ainyx',
        fecha_emision: '3/1/2020',
        fecha_cancelacion: '2/26/2020',
        empleado: 'Austen Berrow',
        total: 560182.0,
      },
      {
        id: 71,
        proveedor: 'Voonder',
        fecha_emision: '11/20/2019',
        fecha_cancelacion: null,
        empleado: 'Darrell Watman',
        total: 650002.08,
      },
      {
        id: 72,
        proveedor: 'Blogtag',
        fecha_emision: '1/23/2020',
        fecha_cancelacion: null,
        empleado: 'Annamarie Tacker',
        total: 237719.33,
      },
      {
        id: 73,
        proveedor: 'Wordware',
        fecha_emision: '7/31/2020',
        fecha_cancelacion: null,
        empleado: 'Gwenora Kopelman',
        total: 760202.3,
      },
      {
        id: 74,
        proveedor: 'Thoughtsphere',
        fecha_emision: '5/12/2020',
        fecha_cancelacion: null,
        empleado: 'Hayden Kingcote',
        total: 613099.0,
      },
      {
        id: 75,
        proveedor: 'Avavee',
        fecha_emision: '6/12/2020',
        fecha_cancelacion: null,
        empleado: 'Gwendolen Walewicz',
        total: 619482.81,
      },
      {
        id: 76,
        proveedor: 'Topicstorm',
        fecha_emision: '11/26/2019',
        fecha_cancelacion: null,
        empleado: 'Evangelin Burch',
        total: 866920.66,
      },
      {
        id: 77,
        proveedor: 'Flashpoint',
        fecha_emision: '4/10/2020',
        fecha_cancelacion: null,
        empleado: 'Neala Walstow',
        total: 529774.26,
      },
      {
        id: 78,
        proveedor: 'Zooveo',
        fecha_emision: '7/29/2020',
        fecha_cancelacion: null,
        empleado: 'Darren Rosenfelder',
        total: 697488.95,
      },
      {
        id: 79,
        proveedor: 'Zooxo',
        fecha_emision: '9/26/2020',
        fecha_cancelacion: null,
        empleado: 'Tildy Gerran',
        total: 943664.94,
      },
      {
        id: 80,
        proveedor: 'Kwimbee',
        fecha_emision: '10/23/2020',
        fecha_cancelacion: null,
        empleado: 'Lita Hassent',
        total: 949058.94,
      },
      {
        id: 81,
        proveedor: 'Shufflebeat',
        fecha_emision: '2/17/2020',
        fecha_cancelacion: null,
        empleado: 'Vinnie Kibby',
        total: 88103.66,
      },
      {
        id: 82,
        proveedor: 'Mynte',
        fecha_emision: '3/18/2020',
        fecha_cancelacion: null,
        empleado: 'Nikolas Sparshatt',
        total: 312303.84,
      },
      {
        id: 83,
        proveedor: 'Kaymbo',
        fecha_emision: '8/3/2020',
        fecha_cancelacion: null,
        empleado: 'Marcy Dye',
        total: 165449.63,
      },
      {
        id: 84,
        proveedor: 'Chatterbridge',
        fecha_emision: '4/16/2020',
        fecha_cancelacion: null,
        empleado: 'Marci Chaters',
        total: 101638.98,
      },
      {
        id: 85,
        proveedor: 'Jabbersphere',
        fecha_emision: '11/11/2020',
        fecha_cancelacion: '6/4/2020',
        empleado: 'Audi Soff',
        total: 747101.71,
      },
      {
        id: 86,
        proveedor: 'Jayo',
        fecha_emision: '1/27/2020',
        fecha_cancelacion: null,
        empleado: 'Dorree Dorwood',
        total: 146651.94,
      },
      {
        id: 87,
        proveedor: 'Meevee',
        fecha_emision: '8/5/2020',
        fecha_cancelacion: null,
        empleado: 'Dillon Son',
        total: 506434.36,
      },
      {
        id: 88,
        proveedor: 'Skynoodle',
        fecha_emision: '10/5/2020',
        fecha_cancelacion: null,
        empleado: 'Lissie Andrez',
        total: 85437.5,
      },
      {
        id: 89,
        proveedor: 'Twitternation',
        fecha_emision: '9/28/2020',
        fecha_cancelacion: null,
        empleado: 'Brandie Clementi',
        total: 765905.09,
      },
      {
        id: 90,
        proveedor: 'Zoomzone',
        fecha_emision: '1/11/2020',
        fecha_cancelacion: null,
        empleado: 'Kenyon Haquin',
        total: 743830.11,
      },
      {
        id: 91,
        proveedor: 'Wordtune',
        fecha_emision: '2/27/2020',
        fecha_cancelacion: null,
        empleado: 'Flynn Mercey',
        total: 437241.98,
      },
      {
        id: 92,
        proveedor: 'Zooveo',
        fecha_emision: '11/30/2019',
        fecha_cancelacion: null,
        empleado: 'Liv McKirdy',
        total: 918932.07,
      },
      {
        id: 93,
        proveedor: 'Demimbu',
        fecha_emision: '12/21/2019',
        fecha_cancelacion: null,
        empleado: 'Rock Glanester',
        total: 675271.6,
      },
      {
        id: 94,
        proveedor: 'Yacero',
        fecha_emision: '12/31/2019',
        fecha_cancelacion: null,
        empleado: 'Dottie Maddy',
        total: 649355.66,
      },
      {
        id: 95,
        proveedor: 'Kare',
        fecha_emision: '3/16/2020',
        fecha_cancelacion: null,
        empleado: 'Sonnnie Longden',
        total: 720555.79,
      },
      {
        id: 96,
        proveedor: 'Trunyx',
        fecha_emision: '11/11/2020',
        fecha_cancelacion: null,
        empleado: 'Amabel Wyon',
        total: 278277.4,
      },
      {
        id: 97,
        proveedor: 'Geba',
        fecha_emision: '8/22/2020',
        fecha_cancelacion: null,
        empleado: 'Toiboid Basham',
        total: 437298.07,
      },
      {
        id: 98,
        proveedor: 'JumpXS',
        fecha_emision: '10/17/2020',
        fecha_cancelacion: null,
        empleado: 'Joann Munden',
        total: 452425.51,
      },
      {
        id: 99,
        proveedor: 'Edgeify',
        fecha_emision: '7/2/2020',
        fecha_cancelacion: null,
        empleado: 'Tann Wicklen',
        total: 973378.61,
      },
      {
        id: 100,
        proveedor: 'Kimia',
        fecha_emision: '2/1/2020',
        fecha_cancelacion: null,
        empleado: 'Roddie Hovey',
        total: 338608.13,
      },
    ];
  }

  dataFillSells(): any[] {
    return [
      {
        id: 1,
        cliente: 'Quinu',
        fecha_emision: '6/2/2020',
        fecha_cancelacion: null,
        empleado: 'Emmye Rikkard',
        total: 202058.17,
      },
      {
        id: 2,
        cliente: 'BlogXS',
        fecha_emision: '1/7/2020',
        fecha_cancelacion: null,
        empleado: 'Ossie McAlester',
        total: 550690.2,
      },
      {
        id: 3,
        cliente: 'Skipfire',
        fecha_emision: '4/24/2020',
        fecha_cancelacion: '10/22/2020',
        empleado: 'Barbette Ryal',
        total: 649755.04,
      },
      {
        id: 4,
        cliente: 'Eamia',
        fecha_emision: '9/29/2020',
        fecha_cancelacion: '12/5/2019',
        empleado: 'Stanislas Torns',
        total: 422489.03,
      },
      {
        id: 5,
        cliente: 'Blogtags',
        fecha_emision: '11/2/2020',
        fecha_cancelacion: '3/25/2020',
        empleado: 'Tabby Wadman',
        total: 83155.15,
      },
      {
        id: 6,
        cliente: 'Roombo',
        fecha_emision: '11/27/2019',
        fecha_cancelacion: '7/12/2020',
        empleado: 'Foster Wilhelmy',
        total: 452371.06,
      },
      {
        id: 7,
        cliente: 'Wordify',
        fecha_emision: '5/27/2020',
        fecha_cancelacion: null,
        empleado: 'Emanuele Siggery',
        total: 436791.81,
      },
      {
        id: 8,
        cliente: 'Fadeo',
        fecha_emision: '5/20/2020',
        fecha_cancelacion: null,
        empleado: 'Myrtle Wyon',
        total: 151668.93,
      },
      {
        id: 9,
        cliente: 'Leenti',
        fecha_emision: '3/22/2020',
        fecha_cancelacion: '7/28/2020',
        empleado: 'Doralia Victor',
        total: 872565.43,
      },
      {
        id: 10,
        cliente: 'Miboo',
        fecha_emision: '12/25/2019',
        fecha_cancelacion: '8/18/2020',
        empleado: 'Rasia Imason',
        total: 273834.68,
      },
      {
        id: 11,
        cliente: 'Ooba',
        fecha_emision: '11/19/2019',
        fecha_cancelacion: null,
        empleado: 'Tito Zanicchelli',
        total: 515463.78,
      },
      {
        id: 12,
        cliente: 'Topiczoom',
        fecha_emision: '6/18/2020',
        fecha_cancelacion: null,
        empleado: 'Marnie Devenny',
        total: 282198.12,
      },
      {
        id: 13,
        cliente: 'Thoughtblab',
        fecha_emision: '1/13/2020',
        fecha_cancelacion: '2/9/2020',
        empleado: 'Blane Llewhellin',
        total: 213248.76,
      },
      {
        id: 14,
        cliente: 'Brainbox',
        fecha_emision: '6/6/2020',
        fecha_cancelacion: null,
        empleado: 'Gibbie Warters',
        total: 963207.73,
      },
      {
        id: 15,
        cliente: 'Demivee',
        fecha_emision: '8/14/2020',
        fecha_cancelacion: '7/1/2020',
        empleado: 'Astrid Dows',
        total: 997197.59,
      },
      {
        id: 16,
        cliente: 'Dabshots',
        fecha_emision: '10/20/2020',
        fecha_cancelacion: null,
        empleado: 'Siward Gregolin',
        total: 225934.88,
      },
      {
        id: 17,
        cliente: 'Feedfire',
        fecha_emision: '8/21/2020',
        fecha_cancelacion: null,
        empleado: 'Steffie Sollner',
        total: 637556.23,
      },
      {
        id: 18,
        cliente: 'Skyndu',
        fecha_emision: '10/25/2020',
        fecha_cancelacion: '12/1/2019',
        empleado: 'Lurette Crysell',
        total: 722609.53,
      },
      {
        id: 19,
        cliente: 'Voomm',
        fecha_emision: '9/12/2020',
        fecha_cancelacion: null,
        empleado: 'Eddi Bickford',
        total: 442852.85,
      },
      {
        id: 20,
        cliente: 'Feedmix',
        fecha_emision: '3/14/2020',
        fecha_cancelacion: null,
        empleado: 'Rubi Bowerbank',
        total: 464859.0,
      },
      {
        id: 21,
        cliente: 'Kare',
        fecha_emision: '4/14/2020',
        fecha_cancelacion: null,
        empleado: 'Tallie Kelberer',
        total: 896071.81,
      },
      {
        id: 22,
        cliente: 'Aibox',
        fecha_emision: '9/3/2020',
        fecha_cancelacion: null,
        empleado: 'Win Wardale',
        total: 149915.1,
      },
      {
        id: 23,
        cliente: 'Jazzy',
        fecha_emision: '6/6/2020',
        fecha_cancelacion: '5/1/2020',
        empleado: 'Moyra Spooner',
        total: 184000.68,
      },
      {
        id: 24,
        cliente: 'Zoonoodle',
        fecha_emision: '1/21/2020',
        fecha_cancelacion: '2/26/2020',
        empleado: 'Raoul Macon',
        total: 124914.71,
      },
      {
        id: 25,
        cliente: 'Topdrive',
        fecha_emision: '9/17/2020',
        fecha_cancelacion: null,
        empleado: 'Garth Camosso',
        total: 377309.05,
      },
      {
        id: 26,
        cliente: 'Babbleopia',
        fecha_emision: '7/5/2020',
        fecha_cancelacion: null,
        empleado: 'Brana Brafferton',
        total: 287069.06,
      },
      {
        id: 27,
        cliente: 'Voolia',
        fecha_emision: '12/30/2019',
        fecha_cancelacion: '11/22/2019',
        empleado: 'Robbert Chamberlaine',
        total: 212441.65,
      },
      {
        id: 28,
        cliente: 'Digitube',
        fecha_emision: '1/5/2020',
        fecha_cancelacion: '5/28/2020',
        empleado: 'Jocko Dabney',
        total: 752890.49,
      },
      {
        id: 29,
        cliente: 'Vinder',
        fecha_emision: '1/5/2020',
        fecha_cancelacion: null,
        empleado: 'Tanitansy Fawdrie',
        total: 732301.0,
      },
      {
        id: 30,
        cliente: 'Demizz',
        fecha_emision: '11/24/2019',
        fecha_cancelacion: null,
        empleado: 'Valentine Hambrick',
        total: 145760.35,
      },
      {
        id: 31,
        cliente: 'Photofeed',
        fecha_emision: '7/7/2020',
        fecha_cancelacion: null,
        empleado: 'Huntington Groll',
        total: 346515.93,
      },
      {
        id: 32,
        cliente: 'Gabvine',
        fecha_emision: '10/22/2020',
        fecha_cancelacion: null,
        empleado: 'Nita Lovelady',
        total: 705521.01,
      },
      {
        id: 33,
        cliente: 'Twitterbridge',
        fecha_emision: '3/29/2020',
        fecha_cancelacion: null,
        empleado: 'Delores Wincer',
        total: 346715.24,
      },
      {
        id: 34,
        cliente: 'Browsedrive',
        fecha_emision: '6/2/2020',
        fecha_cancelacion: '5/31/2020',
        empleado: 'Irvin Ebbutt',
        total: 821396.66,
      },
      {
        id: 35,
        cliente: 'Skyble',
        fecha_emision: '2/16/2020',
        fecha_cancelacion: '2/27/2020',
        empleado: 'Renaud Rakestraw',
        total: 154790.39,
      },
      {
        id: 36,
        cliente: 'Oyoyo',
        fecha_emision: '10/28/2020',
        fecha_cancelacion: null,
        empleado: 'Clywd Coard',
        total: 583781.07,
      },
      {
        id: 37,
        cliente: 'Zoomcast',
        fecha_emision: '5/23/2020',
        fecha_cancelacion: null,
        empleado: 'Devland Carbin',
        total: 289314.45,
      },
      {
        id: 38,
        cliente: 'Jatri',
        fecha_emision: '1/14/2020',
        fecha_cancelacion: '12/1/2019',
        empleado: 'Aeriel Di Franceschi',
        total: 372213.4,
      },
      {
        id: 39,
        cliente: 'Tazz',
        fecha_emision: '7/15/2020',
        fecha_cancelacion: null,
        empleado: 'Devinne Croad',
        total: 768286.66,
      },
      {
        id: 40,
        cliente: 'Skimia',
        fecha_emision: '3/8/2020',
        fecha_cancelacion: '8/6/2020',
        empleado: 'Jena Leebetter',
        total: 978971.62,
      },
      {
        id: 41,
        cliente: 'Bubblebox',
        fecha_emision: '1/1/2020',
        fecha_cancelacion: null,
        empleado: 'Antons Rzehorz',
        total: 157219.66,
      },
      {
        id: 42,
        cliente: 'Tavu',
        fecha_emision: '10/17/2020',
        fecha_cancelacion: null,
        empleado: 'Kelbee Caulier',
        total: 831852.82,
      },
      {
        id: 43,
        cliente: 'Photospace',
        fecha_emision: '5/2/2020',
        fecha_cancelacion: '6/11/2020',
        empleado: 'Daryn Mulvaney',
        total: 971101.68,
      },
      {
        id: 44,
        cliente: 'Camimbo',
        fecha_emision: '9/9/2020',
        fecha_cancelacion: null,
        empleado: 'Skylar Murcott',
        total: 576599.29,
      },
      {
        id: 45,
        cliente: 'Meevee',
        fecha_emision: '12/5/2019',
        fecha_cancelacion: '12/8/2019',
        empleado: 'Antonius Wasielewski',
        total: 532533.8,
      },
      {
        id: 46,
        cliente: 'Rhynoodle',
        fecha_emision: '2/9/2020',
        fecha_cancelacion: '8/20/2020',
        empleado: 'Ingaberg Flieg',
        total: 438819.08,
      },
      {
        id: 47,
        cliente: 'Voolith',
        fecha_emision: '7/16/2020',
        fecha_cancelacion: '10/10/2020',
        empleado: 'Therese Slyman',
        total: 958729.66,
      },
      {
        id: 48,
        cliente: 'Yadel',
        fecha_emision: '8/15/2020',
        fecha_cancelacion: null,
        empleado: 'Marietta Matignon',
        total: 290984.97,
      },
      {
        id: 49,
        cliente: 'Jabbertype',
        fecha_emision: '7/31/2020',
        fecha_cancelacion: null,
        empleado: 'Alameda Rosie',
        total: 848667.53,
      },
      {
        id: 50,
        cliente: 'Thoughtworks',
        fecha_emision: '12/2/2019',
        fecha_cancelacion: '10/9/2020',
        empleado: 'Ernestine Danick',
        total: 399631.7,
      },
      {
        id: 51,
        cliente: 'Kimia',
        fecha_emision: '11/8/2020',
        fecha_cancelacion: '3/23/2020',
        empleado: 'Shelli Knoble',
        total: 527776.0,
      },
      {
        id: 52,
        cliente: 'Fivechat',
        fecha_emision: '5/17/2020',
        fecha_cancelacion: null,
        empleado: 'Jayne Parratt',
        total: 348512.2,
      },
      {
        id: 53,
        cliente: 'Meetz',
        fecha_emision: '12/3/2019',
        fecha_cancelacion: '10/31/2020',
        empleado: 'Carney Knuckles',
        total: 305245.7,
      },
      {
        id: 54,
        cliente: 'Eamia',
        fecha_emision: '8/15/2020',
        fecha_cancelacion: null,
        empleado: 'Hadria Evenett',
        total: 444219.55,
      },
      {
        id: 55,
        cliente: 'Demimbu',
        fecha_emision: '12/29/2019',
        fecha_cancelacion: '3/15/2020',
        empleado: 'Irina OFerris',
        total: 646818.01,
      },
      {
        id: 56,
        cliente: 'Mydeo',
        fecha_emision: '3/5/2020',
        fecha_cancelacion: '12/14/2019',
        empleado: 'Tris Timmins',
        total: 680729.16,
      },
      {
        id: 57,
        cliente: 'Oyondu',
        fecha_emision: '2/18/2020',
        fecha_cancelacion: null,
        empleado: 'Russell Pickerell',
        total: 609658.81,
      },
      {
        id: 58,
        cliente: 'Livefish',
        fecha_emision: '8/5/2020',
        fecha_cancelacion: '3/8/2020',
        empleado: 'Klarrisa Goldsby',
        total: 931405.89,
      },
      {
        id: 59,
        cliente: 'Jetwire',
        fecha_emision: '6/14/2020',
        fecha_cancelacion: null,
        empleado: 'Isis Lampel',
        total: 871608.8,
      },
      {
        id: 60,
        cliente: 'Photojam',
        fecha_emision: '5/1/2020',
        fecha_cancelacion: '4/28/2020',
        empleado: 'Nikolos Garlicke',
        total: 494281.07,
      },
      {
        id: 61,
        cliente: 'Voonix',
        fecha_emision: '9/29/2020',
        fecha_cancelacion: null,
        empleado: 'Hewie Glencrash',
        total: 274057.2,
      },
      {
        id: 62,
        cliente: 'Twimm',
        fecha_emision: '6/17/2020',
        fecha_cancelacion: null,
        empleado: 'Terence Dumbelton',
        total: 172529.38,
      },
      {
        id: 63,
        cliente: 'Jatri',
        fecha_emision: '9/27/2020',
        fecha_cancelacion: null,
        empleado: 'Rinaldo Stoacley',
        total: 711229.0,
      },
      {
        id: 64,
        cliente: 'Bubblemix',
        fecha_emision: '10/13/2020',
        fecha_cancelacion: null,
        empleado: 'Tull Missen',
        total: 514545.81,
      },
      {
        id: 65,
        cliente: 'Aimbu',
        fecha_emision: '12/1/2019',
        fecha_cancelacion: '5/19/2020',
        empleado: 'Port Pinock',
        total: 404393.62,
      },
      {
        id: 66,
        cliente: 'DabZ',
        fecha_emision: '7/29/2020',
        fecha_cancelacion: null,
        empleado: 'Constantin Janouch',
        total: 995204.66,
      },
      {
        id: 67,
        cliente: 'Buzzdog',
        fecha_emision: '7/5/2020',
        fecha_cancelacion: null,
        empleado: 'Joy Boutellier',
        total: 968206.8,
      },
      {
        id: 68,
        cliente: 'Voonte',
        fecha_emision: '2/16/2020',
        fecha_cancelacion: null,
        empleado: 'Evangelia Santello',
        total: 541445.14,
      },
      {
        id: 69,
        cliente: 'Twimm',
        fecha_emision: '12/26/2019',
        fecha_cancelacion: '8/30/2020',
        empleado: 'Meara OHanley',
        total: 470939.54,
      },
      {
        id: 70,
        cliente: 'Bubbletube',
        fecha_emision: '8/8/2020',
        fecha_cancelacion: null,
        empleado: 'Marji Stoffels',
        total: 552757.25,
      },
      {
        id: 71,
        cliente: 'Dazzlesphere',
        fecha_emision: '9/11/2020',
        fecha_cancelacion: null,
        empleado: 'Auberon Vedyasov',
        total: 558442.39,
      },
      {
        id: 72,
        cliente: 'Katz',
        fecha_emision: '10/13/2020',
        fecha_cancelacion: null,
        empleado: 'Hector Muldownie',
        total: 450320.12,
      },
      {
        id: 73,
        cliente: 'Jayo',
        fecha_emision: '7/7/2020',
        fecha_cancelacion: '8/6/2020',
        empleado: 'Nehemiah Keeltagh',
        total: 604366.55,
      },
      {
        id: 74,
        cliente: 'Cogibox',
        fecha_emision: '1/28/2020',
        fecha_cancelacion: '2/15/2020',
        empleado: 'Melloney Lafayette',
        total: 509886.0,
      },
      {
        id: 75,
        cliente: 'Zoonder',
        fecha_emision: '4/2/2020',
        fecha_cancelacion: null,
        empleado: 'Marney Hinckley',
        total: 566110.1,
      },
      {
        id: 76,
        cliente: 'Skibox',
        fecha_emision: '2/10/2020',
        fecha_cancelacion: '3/29/2020',
        empleado: 'Bartram Huebner',
        total: 842207.24,
      },
      {
        id: 77,
        cliente: 'Flipbug',
        fecha_emision: '3/17/2020',
        fecha_cancelacion: '7/11/2020',
        empleado: 'Queenie Golborne',
        total: 95284.09,
      },
      {
        id: 78,
        cliente: 'Skimia',
        fecha_emision: '5/25/2020',
        fecha_cancelacion: null,
        empleado: 'Ad Signori',
        total: 958563.26,
      },
      {
        id: 79,
        cliente: 'Fivebridge',
        fecha_emision: '1/15/2020',
        fecha_cancelacion: '6/18/2020',
        empleado: 'Mord Ratke',
        total: 184935.0,
      },
      {
        id: 80,
        cliente: 'Kwilith',
        fecha_emision: '10/11/2020',
        fecha_cancelacion: '10/11/2020',
        empleado: 'Aretha Ethington',
        total: 326675.76,
      },
      {
        id: 81,
        cliente: 'Skilith',
        fecha_emision: '8/4/2020',
        fecha_cancelacion: null,
        empleado: 'Gayla Gethen',
        total: 76461.3,
      },
      {
        id: 82,
        cliente: 'Yodoo',
        fecha_emision: '10/1/2020',
        fecha_cancelacion: '7/6/2020',
        empleado: 'Flor Giannini',
        total: 861429.62,
      },
      {
        id: 83,
        cliente: 'Blognation',
        fecha_emision: '8/3/2020',
        fecha_cancelacion: '12/10/2019',
        empleado: 'Lorrayne Denisyuk',
        total: 593217.62,
      },
      {
        id: 84,
        cliente: 'Wordware',
        fecha_emision: '3/16/2020',
        fecha_cancelacion: '7/29/2020',
        empleado: 'Temp Tumility',
        total: 844967.0,
      },
      {
        id: 85,
        cliente: 'Voonte',
        fecha_emision: '11/8/2020',
        fecha_cancelacion: '2/19/2020',
        empleado: 'Eduino Allwood',
        total: 268739.9,
      },
      {
        id: 86,
        cliente: 'Skiptube',
        fecha_emision: '6/10/2020',
        fecha_cancelacion: '1/21/2020',
        empleado: 'Judye Matfield',
        total: 374321.22,
      },
      {
        id: 87,
        cliente: 'Jabbertype',
        fecha_emision: '7/22/2020',
        fecha_cancelacion: null,
        empleado: 'Leslie Cutten',
        total: 54166.39,
      },
      {
        id: 88,
        cliente: 'Topdrive',
        fecha_emision: '11/28/2019',
        fecha_cancelacion: '7/26/2020',
        empleado: 'Patrizius Ferrini',
        total: 816477.0,
      },
      {
        id: 89,
        cliente: 'Vitz',
        fecha_emision: '11/6/2020',
        fecha_cancelacion: '7/2/2020',
        empleado: 'Evangelina Bradmore',
        total: 93257.39,
      },
      {
        id: 90,
        cliente: 'Thoughtstorm',
        fecha_emision: '1/3/2020',
        fecha_cancelacion: null,
        empleado: 'Arlina Chiommienti',
        total: 597938.96,
      },
      {
        id: 91,
        cliente: 'Realbuzz',
        fecha_emision: '10/3/2020',
        fecha_cancelacion: null,
        empleado: 'Dalli Barlthrop',
        total: 819165.47,
      },
      {
        id: 92,
        cliente: 'Centizu',
        fecha_emision: '5/12/2020',
        fecha_cancelacion: null,
        empleado: 'Horten Brougham',
        total: 995526.72,
      },
      {
        id: 93,
        cliente: 'Skilith',
        fecha_emision: '6/3/2020',
        fecha_cancelacion: '11/27/2019',
        empleado: 'Sally Fussie',
        total: 255262.83,
      },
      {
        id: 94,
        cliente: 'Kwilith',
        fecha_emision: '11/30/2019',
        fecha_cancelacion: '7/2/2020',
        empleado: 'Edythe MacKey',
        total: 629419.33,
      },
      {
        id: 95,
        cliente: 'Agimba',
        fecha_emision: '8/17/2020',
        fecha_cancelacion: '8/24/2020',
        empleado: 'Merl Puckey',
        total: 361150.19,
      },
      {
        id: 96,
        cliente: 'Youspan',
        fecha_emision: '7/23/2020',
        fecha_cancelacion: '4/15/2020',
        empleado: 'Mitchell Alldis',
        total: 498152.94,
      },
      {
        id: 97,
        cliente: 'Twimbo',
        fecha_emision: '7/9/2020',
        fecha_cancelacion: '11/27/2019',
        empleado: 'Dari Ffrench',
        total: 405087.38,
      },
      {
        id: 98,
        cliente: 'Dynabox',
        fecha_emision: '1/31/2020',
        fecha_cancelacion: '8/17/2020',
        empleado: 'Cad Ratke',
        total: 421944.25,
      },
      {
        id: 99,
        cliente: 'Aimbo',
        fecha_emision: '10/24/2020',
        fecha_cancelacion: null,
        empleado: 'Darleen Verheyden',
        total: 63897.86,
      },
      {
        id: 100,
        cliente: 'Voolia',
        fecha_emision: '7/30/2020',
        fecha_cancelacion: '2/14/2020',
        empleado: 'Jenine Schulken',
        total: 277990.32,
      },
    ];
  }
}
